### PR TITLE
Replace deprecated PyEval_CallObject in tf2_py

### LINKED ISSUE #568: Fails to build on Python 3.13: PyEval_CallObject removed
https://github.com/ros/geometry2/blob/6df9e94363061a24ba890a6ff29771a96b0d756b/tf2_py/src/tf2_py.cpp#L89

```
cd /<<PKGBUILDDIR>>/.pybuild/cpython3_3.13/build/tf2_ros && /usr/bin/c++ -DBOOST_ATOMIC_DYN_LINK -DBOOST_ATOMIC_NO_LIB -DBOOST_SYSTEM_DYN_LINK -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_NO_LIB -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"tf2_ros\" -Dtf2_ros_EXPORTS -I/<<PKGBUILDDIR>>/tf2_ros/include -I/<<PKGBUILDDIR>>/.pybuild/cpython3_3.13/build/devel/include -I/<<PKGBUILDDIR>>/tf2/include -I/<<PKGBUILDDIR>>/tf2_msgs/include -I/usr/include/xmlrpcpp -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -mbranch-protection=standard -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -MD -MT tf2_ros/CMakeFiles/tf2_ros.dir/src/static_transform_broadcaster.cpp.o -MF CMakeFiles/tf2_ros.dir/src/static_transform_broadcaster.cpp.o.d -o CMakeFiles/tf2_ros.dir/src/static_transform_broadcaster.cpp.o -c /<<PKGBUILDDIR>>/tf2_ros/src/static_transform_broadcaster.cpp
/<<PKGBUILDDIR>>/tf2_py/src/tf2_py.cpp: In function ‘PyObject* transform_converter(const geometry_msgs::TransformStamped*)’:
/<<PKGBUILDDIR>>/tf2_py/src/tf2_py.cpp:89:11: error: ‘PyEval_CallObject’ was not declared in this scope; did you mean 'PyObject_CallObject’?
   89 |   pinst = PyEval_CallObject(pclass, pargs);
      |           ^~~~~~~~~~~~~~~~~
      |           PyObject_CallObject
make[3]: *** [tf2_py/CMakeFiles/tf2_py.dir/build.make:79: tf2_py/CMakeFiles/tf2_py.dir/src/tf2_py.cpp.o] Error 1
```

https://docs.python.org/3.13/whatsnew/3.13.html#removed-c-apis

### PR DESCRIPTION
**Pull request by kenstowe**
Replacing deprecated PyEval_CallObject with PyObject_CallObject. 

Fixes #568

### CODE REVIEW

**Comment by tfoote** [comment]
This is useful to resolve, what is the maximum backwards compatibility of this change?

**Comment by kenstowe** [comment]
PyObject_CallObject() has existed since Python 3.0 and so is backward compatible till at least then. It is also part of the Stable ABI and should remain compatible across all Python 3.x versions. 

If this commit is merged. Could a tag also be created? I'm building on Arch and a tag would allow me to submit a PR to fix this issue on the AUR ros-noetic-tf2_py package.

**Review by sloretz — APPROVED** [review]
> PyEval_CallObject() is identical to PyObject_CallObject().  Only difference is it's a macro or function.

https://bugs.python.org/issue29548

**Review by tfoote — APPROVED** [review]
Thanks for the clarification. LGTM

**Comment by sloretz** [comment]
Pulls: https://github.com/ros/geometry2/pull/575
Gist: https://gist.githubusercontent.com/sloretz/6d2ba92106cd43b987354f7f2d2c0372/raw/369523f2feeec725d8132335707966fe4ce648ba/ros2.repos
BUILD args:  --packages-up-to tf2_py
TEST args:  --packages-select tf2_py
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/15138
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/22471/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16723/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1996/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/23257/)

**Comment by sloretz** [comment]
Edit: Ohhh I missed that this is ROS 1

**Comment by sloretz** [comment]
Thank you for the PR!
